app:
  name: CurrencyExchangeApp
  port: ":3000"

database:
  dsn: "root:123456@tcp(127.0.0.1:3307)/testdb?charset=utf8mb4&parseTime=True&loc=Local"
  MaxIdleConns: 10
  MaxOpenCons: 100

redis:
  addr: "localhost:6379"
  DB: 0
  Password: ""
rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"
  queue: "like.queue"